# Generated by Django 3.0.5 on 2020-04-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlikes',
            old_name='blogpost',
            new_name='blog',
        ),
    ]
